--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/Lifesteal
build-by-default: true
branches:
- main
projects:
  Lifesteal:
    path: ""
    libs:
      - src: customiesdevs/customies/Customies
        version: ^1.3.2
...
